name: Buda Zapier

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - run: npm ci
    - run: npm test
      env:
        CI: true

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - run: npm install -g zapier-platform-cli
    - run: npm ci
    - run: npm run prepare
    - run: npm run deploy
      env:
        ENV: production
        ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}

