name: Buda Zapier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  tests:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - run: npm ci
    - run: npm test
      env:
        CI: true

  build_deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - run: npm install -g zapier-platform-cli
    - run: npm ci
    - name: Deploy Staging
      run: zapier push
      if: ${{ github.event_name == 'push' }}
      env:
        ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}

    - name: Deploy Production
      run: zapier push
      if: ${{ github.event_name == 'release' }}
      env:
        ZAPIER_CURRENT_APP_FILE: .zapierapprc-prod
        ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}

